/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package polskaad1340;

import java.awt.GridLayout;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author Kuba
 */
public class OknoMapy extends javax.swing.JFrame {

    public ArrayList<ArrayList<JLabel>> tileGrid;
    
    public void createTileGrid(int size, int tileSize)
    {
        tileGrid = new ArrayList<>(size);
        for (int i = 0; i < size; i++) {
            
            ArrayList<JLabel> tileGridRow = new ArrayList<>(size);
            
            for (int j = 0; j < size; j++) {
                int num = i*size+j;
                String path = "/images/"+num+".png";
                System.out.println("i:"+i+"j:"+j+"path:"+path);
                ImageIcon ii = new ImageIcon(getClass().getResource(path));
                
                JLabel jl = new JLabel(ii);
                jl.setSize(tileSize,tileSize);
                tileGridRow.add(jl);
            }
            
            tileGrid.add(tileGridRow);
            
        }
        
    }
    
    public void addTileGridToWindow()
    {
        GridLayout gl = (GridLayout) getContentPane().getLayout();
            gl.setRows(tileGrid.size());
            gl.setColumns(tileGrid.size());
        
        for (int i = 0; i < tileGrid.size(); i++) {
            ArrayList<JLabel> arrayList = tileGrid.get(i);
            for (int j = 0; j < arrayList.size(); j++) {
                JLabel jLabel = arrayList.get(j);
                getContentPane().add(jLabel);
            }
        }
    }
    
    /**
     * Creates new form OknoMapy
     */
    public OknoMapy() {
        initComponents();
        createTileGrid(20,32);
        addTileGridToWindow();
        System.out.print("done");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OknoMapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OknoMapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OknoMapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OknoMapy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OknoMapy().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
